// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeJiZaGc6VRNPgJ1cN6akIywz1BNMZCt8',
    appId: '1:925059890787:web:4f6c395ec8046ddb4d0256',
    messagingSenderId: '925059890787',
    projectId: 'craftconnect-2301c',
    authDomain: 'craftconnect-2301c.firebaseapp.com',
    storageBucket: 'craftconnect-2301c.appspot.app',
    measurementId: 'G-GZRPH0663X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeHZm6R0_v0-Zp_1LpCVNT50RoUTES1f0',
    appId: '1:925059890787:android:8faa5bc9f870fc414d0256',
    messagingSenderId: '925059890787',
    projectId: 'craftconnect-2301c',
    storageBucket: 'craftconnect-2301c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTRwG00sbrssojAooiuo0zwrtu8hGOvoA',
    appId: '1:925059890787:ios:2346e05a511c362b4d0256',
    messagingSenderId: '925059890787',
    projectId: 'craftconnect-2301c',
    storageBucket: 'craftconnect-2301c.firebasestorage.app',
    iosBundleId: 'com.example.craftconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTRwG00sbrssojAooiuo0zwrtu8hGOvoA',
    appId: '1:925059890787:ios:2346e05a511c362b4d0256',
    messagingSenderId: '925059890787',
    projectId: 'craftconnect-2301c',
    storageBucket: 'craftconnect-2301c.firebasestorage.app',
    iosBundleId: 'com.example.craftconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeJiZaGc6VRNPgJ1cN6akIywz1BNMZCt8',
    appId: '1:925059890787:web:ed3e968392eb36804d0256',
    messagingSenderId: '925059890787',
    projectId: 'craftconnect-2301c',
    authDomain: 'craftconnect-2301c.firebaseapp.com',
    storageBucket: 'craftconnect-2301c.firebasestorage.app',
    measurementId: 'G-SWNL301ZS9',
  );

}